# Generated by Django 2.1.7 on 2019-03-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_no', models.IntegerField(default=0, unique=True)),
                ('bank_statement', models.FileField(db_index=True, upload_to='bank_statements')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_formalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default=None, max_length=100)),
                ('ac_no', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tracked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('address', models.TextField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('address', models.TextField(default=None, max_length=100)),
            ],
        ),
    ]
