# Generated by Django 2.1.7 on 2019-03-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('address', models.TextField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_no', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_formalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default=None, max_length=100)),
                ('ac_no', models.IntegerField(default=0, unique=True)),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='bank_statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('lEdu', models.IntegerField(default=0)),
                ('hEdu', models.IntegerField(default=0)),
                ('area', models.CharField(default=0, max_length=100)),
                ('jewellery', models.IntegerField(default=0)),
                ('cars', models.IntegerField(default=0)),
                ('bikes', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('debit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='predicted_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('lEdu', models.IntegerField(default=0)),
                ('hEdu', models.IntegerField(default=0)),
                ('area', models.CharField(default=0, max_length=100)),
                ('jewellery', models.IntegerField(default=0)),
                ('cars', models.IntegerField(default=0)),
                ('bikes', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('debit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('fraud', models.BooleanField(default=0)),
                ('predicted_features', models.ForeignKey(on_delete='models.CASCADE', to='fraud.predicted_features')),
            ],
        ),
        migrations.CreateModel(
            name='tracked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('address', models.TextField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bank_details',
            name='bank_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fraud.bank_statement'),
        ),
    ]
