# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('lEdu', models.IntegerField(default=0)),
                ('hEdu', models.IntegerField(default=0)),
                ('area', models.CharField(default=0, max_length=100)),
                ('jewellery', models.IntegerField(default=0)),
                ('cars', models.IntegerField(default=0)),
                ('bikes', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('debit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='predicted_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('lEdu', models.IntegerField(default=0)),
                ('hEdu', models.IntegerField(default=0)),
                ('area', models.CharField(default=0, max_length=100)),
                ('jewellery', models.IntegerField(default=0)),
                ('cars', models.IntegerField(default=0)),
                ('bikes', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('debit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('fraud', models.BooleanField(default=0)),
                ('predicted_features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fraud.predicted_features')),
            ],
        ),
        migrations.RenameModel(
            old_name='user_details',
            new_name='Aadhar',
        ),
        migrations.AddField(
            model_name='bank_formalities',
            name='aadhar_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='bank_details',
            name='bank_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fraud.bank_statement'),
        ),
    ]
