# Generated by Django 2.1.7 on 2019-03-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('address', models.TextField(default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
        migrations.AddField(
            model_name='bank_formalities',
            name='aadhar_no',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
