# Generated by Django 2.1.7 on 2019-03-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_aadhar_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhar',
            name='done',
        ),
    ]
