# Generated by Django 2.1.7 on 2019-03-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_auto_20190302_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_details',
            name='bank_statement',
            field=models.FileField(upload_to='bank_statements'),
        ),
    ]
