# Generated by Django 2.1.7 on 2019-03-02 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0003_auto_20190302_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharno', models.IntegerField(default=0, unique=True)),
                ('lEdu', models.IntegerField(default=0)),
                ('hEdu', models.IntegerField(default=0)),
                ('area', models.CharField(default=0, max_length=100)),
                ('jewellery', models.IntegerField(default=0)),
                ('cars', models.IntegerField(default=0)),
                ('bikes', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('debit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='bank_details',
            name='bank_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fraud.bank_statement'),
        ),
    ]
