# Generated by Django 2.1.7 on 2019-03-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0003_remove_aadhar_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhar',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
