# Generated by Django 2.1.7 on 2019-03-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0004_auto_20190302_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_statement',
            old_name='aadharno',
            new_name='aadhar_no',
        ),
    ]
