# Generated by Django 2.1.7 on 2019-03-03 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0006_auto_20190303_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0)),
                ('reason', models.TextField(default='a')),
            ],
        ),
        migrations.CreateModel(
            name='reportedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='documents/')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fraud.reportedImages'),
        ),
    ]
