# Generated by Django 2.1.7 on 2019-03-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0007_auto_20190303_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='images',
        ),
        migrations.AddField(
            model_name='report',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='holidays/'),
        ),
        migrations.DeleteModel(
            name='reportedImages',
        ),
    ]
