# Generated by Django 2.1.7 on 2019-03-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0009_auto_20190303_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
