# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-02 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=report.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('address', models.TextField(default=None, max_length=100)),
                ('statement', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='report.Report'),
        ),
    ]
